### ISSUE TITLE
Error reading application data on build, run, and clean

### ISSUE THREAD

**Issue by JhOnNeY** [NPC-Studio/adam#2]
attempting to run `adam build -g "/Applications/GameMaker Studio 2.app"` or `adam run` or any command other than `help` yields:

`adam error: reading application data invalid value: integer '-1', expected usize at line 478 column 17
aborting
`

I know the GMS2 runtime is supposed to be exactly `2.3.0.401` but I just saw that the build.rs file was 'updated to work on different runtimes and weirder projects' and hoped it would work 🤷 

OS: MacOS BigSur 11.6
GMS2 IDE: v2.3.5.589
GMS2 Runtime: v2.3.5.458

**Comment by sanbox-irl** [comment]
@JhOnNeY could you try on current?

**Comment by JhOnNeY** [comment]
Yes, It may be a few days before I get to it though.

**Comment by JhOnNeY** [comment]
Okay It's now attempting to build with a config file 👍 

Just gotta figure out how to get it to build successfully 🤔 

Thanks for following up!
