### ISSUE TITLE
[Question] Running in the default GitHub Actions Runner?

### ISSUE THREAD

**Issue by shichen85** [NPC-Studio/adam#5]
Hello, this is a tangentially related question, and please feel free to close if the maintainer deems it irrelevant: 

I wonder if anyone has built their YYP project in the default GitHub Actions [windows-2019 runner](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md)? 

I was able to follow the [GMS Manual](https://manual.yoyogames.com/#t=Settings%2FBuilding_via_Command_Line.htm) and build iOS and Android exports, but for Windows exports, I am finding that Igor skipped compiling the shaders that my projects have into the `Shader\HLSL11\*.shdata` files that normally appear in the IDE cache directory.

I am curious if anyone has run into the same issues while using Adam.  

Thanks in advance!

**Comment by sanbox-irl** [comment]
Yup -- it's a bit complex, but essentially you need to build yourself a "blob" of data, including license files, which you point Adam to. The options `license-path` and what not are there exactly for that (ie, on Fields of Mistria, we do exactly that). If you want to reach out to me at sanbox_irl#7777 on Discord, I can walk you through it more particularly

**Comment by shichen85** [comment]
Thank you for the reply! We will continue the conversation on Discord then!
